### ISSUE TITLE
Кэшировать иконки видео и плейлистов

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#148]
Полезная задача в принципе. Но особенно актуальная для релазиации режима оффлайн https://github.com/sadr0b0t/yashlang/issues/142

Пусть сразу будет отдельным тикетом.

Еще одна история с иконками-превью роликов
> Кстати, про режим "оффлайн". Вопрос - вытягивать в таком режиме иконки с превью видео. Если интернета нет, то их и так не будет (но будет попытка загрузить их массово - это тормоза). Если есть, то пользователь может ожидать, что в режиме оффлайн плеер за ними не полезет. Это можно сделать настройкой. Еще можно, кстати, кэшировать превьюшки для роликов с офллайн-потоками.

- Ссылки на иконки в базе можно не хранить
- Название файла с иконкой - video_id.png playlist_id.png (в отдельных каталогах или с превиксом video_xx, pl_xx)
- Управвление кэшированными иконками - в отдельной вкладке - там же, где сейчас закачки потоков
-- показать размер
-- удалить весь кэш
-- удалить лишние файлы (из имени файла придется выуживать id видео/плейлиста и каждый в базе сверять)
-- удалить кэш для файлов, у которых нет потоков оффлайн
-- обновить кэш (для тех файлов, которые уже есть - тоже через запрос в базу по id)
-- выкачать иконки для всех файлов, у которых есть оффлайн-поток
- Простой вариант с обновлением: удалить весь кэш, выкачать кэш для файлов с потоками оффлайн
- Вариант: сохранять кэш иконок вообще для всех видео, которые появляются в любом списке. Потом если он привысит разумные пределы чистить его  через "удалить кэш для роликов, у которых нет потоков оффлайн". Скорее всего по сравнению с закачанными потоками там вообще будут копейки.

Для плейлистов иконки нужно просто вообще для всех кэшировать.

И да, для режима плеера https://github.com/sadr0b0t/yashlang/issues/134 нужно качать иконки видео размером побольше, т.к. их растягиваем вместо потока аудио на весь экран.

**Comment by sadr0b0t** [comment]
Размер иконок:
- плейлисты: вытянуть максимальный (их очень ограниченное количество всё равно)

- для видео:
-- минимальный размер - посмотреть размеры иконок в списках в вариенте для планшетов xlarge (должно быть точно не меньше)
-- теоретически этот вариант можно рассматривать для кэширования иконок без разбора для всех роликов
- больше может потребоваться для режима аудио-плеера - там их нужно растягивать на весь экран
-- тянуть и кэшировать для всех роликов подряд без разбора может быть уже заметный по использованию ресурсов вариант
-- но нужно еще посмотреть, как там с размерами
-- возможно, большие версии картинок как раз кэшировать для оффлайн роликов, а маленькие - для всех подряд

**Comment by sadr0b0t** [comment]
Почищу немного код, оставлю здесь. Сейчас иконки роликов беру из API, но раньше в самом начале собирался брать их вручную. В VideoThumbManager остался неиспользуемый код.

~~~java
    //private static final String THUMB_URL_TEMPLATE = "https://img.youtube.com/vi/%id%/sddefault.jpg";
    private static final String THUMB_URL_TEMPLATE = "https://img.youtube.com/vi/%id%/default.jpg";

    // http://img.youtube.com/vi/<insert-youtube-video-id-here>/default.jpg
    // http://img.youtube.com/vi/<insert-youtube-video-id-here>/hqdefault.jpg
    // http://img.youtube.com/vi/<insert-youtube-video-id-here>/mqdefault.jpg
    // http://img.youtube.com/vi/<insert-youtube-video-id-here>/sddefault.jpg
    // http://img.youtube.com/vi/<insert-youtube-video-id-here>/maxresdefault.jpg


    /**
     * Load thumbnail for youtube video
     * @param ytId youtube video id
     * @return video thumbnail as bitmap
     * @throws IOException
     */
    public Bitmap loadVideoThumb(final String ytId) throws IOException {
        // 1) YouTube data api (Android):
        // https://github.com/youtube/api-samples/tree/master/java
        // (похоже, хотят обращаться к ютюб-сервисам, установленным на телефоне;
        // скорее всего выберем данунах, проще тягать иконки по шаблону URL и парсить страничку с поиском)
        // https://developers.google.com/youtube/v3/quickstart/android
        // build.gradle:
        //     compile('com.google.apis:google-api-services-youtube:v3-rev209-1.25.0') {
        //        exclude group: 'org.apache.httpcomponents'
        //    }
        // AndroidManifest.xml
        //     <uses-permission android:name="android.permission.INTERNET" />
        //    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

        // 2) Вручную по шаблону
        // https://www.thewebtaylor.com/articles/how-to-get-a-youtube-videos-thumbnail-image-in-high-quality
        // http://img.youtube.com/vi/<insert-youtube-video-id-here>/hqdefault.jpg
        // https://img.youtube.com/vi/KguUtafZtN8/sddefault.jpg

        return loadBitmap(THUMB_URL_TEMPLATE.replace("%id%", ytId));
    }
~~~

**Comment by sadr0b0t** [comment]
https://github.com/sadr0b0t/yashlang/commit/b302e96a08add054d24ff270371bf6aec97f2375
https://github.com/sadr0b0t/yashlang/commit/c1f5f69d8ada088cb2b9d1eeb6ab773299256fbe

**Comment by sadr0b0t** [comment]
Поймал эксепшен при попытке закэшировать иконку "Три толстяка"

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
	at su.sadrobot.yashlang.controller.ThumbManager.saveBitmap(ThumbManager.java:121)
	at su.sadrobot.yashlang.controller.ThumbManager.loadVideoThumb(ThumbManager.java:155)
	at su.sadrobot.yashlang.view.VideoItemPagedListAdapter$5.run(VideoItemPagedListAdapter.java:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
~~~

Исправляю здесь, пока не зарелизил

**Comment by sadr0b0t** [comment]
> Поймал эксепшен при попытке закэшировать иконку "Три толстяка"

фикс: https://github.com/sadr0b0t/yashlang/commit/52e1dd1ec5455ec04d9190f55421422de0891eff

плюс небольшой рефактор для единообразия сюда же: https://github.com/sadr0b0t/yashlang/commit/a2536a35da169b2e378803bcfc5fd5400621e498
