### ISSUE TITLE
Позволить выбирать качество видео

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#15]
Добавить возможность выбирать видео-поток с нужным качеством (возможно, также добавить опцию выбора только аудио-потока - в этом случае на экране показывать только картинку с иконкой видео или картинку-заглушку).

Технически - выпадающее меню в полосе управления плеером, как в ютюбе.

**Comment by sadr0b0t** [comment]
Предварительно: https://github.com/sadr0b0t/yashlang/commit/b89c415ba3d71a0ac81c40f5d54b7fad249eac27 - выбирать для проигрывания поток с наулучшим качеством из доступных (последний в списке доступных).

**Comment by sadr0b0t** [comment]
С последним патчем не играют некоторые ролики - вот два:

Крылатый, мохнатый да масленый (1990) | Советский мультфильм
https://www.youtube.com/watch?v=GOZGa68CtaE

С патчем выбирается 720p MPEG-4 и он почему-то не играет. Без патча выбирается 360p MPEG-4 и он играет

extractor.getVideoStreams()
~~~
2020-10-02 23:06:13.279 31431-1878/su.sadrobot.yashlang I/System.out: 360p MPEG-4 video/mp4 mp4
2020-10-02 23:06:13.280 31431-1878/su.sadrobot.yashlang I/System.out: 720p MPEG-4 video/mp4 mp4
~~~

более полный список стримов (судя по всему, с отдельной звуковой дорожкой):

extractor.getVideoOnlyStreams():

~~~
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 720p WebM video/webm webm
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 480p MPEG-4 video/mp4 mp4
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 480p WebM video/webm webm
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 240p MPEG-4 video/mp4 mp4
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 240p WebM video/webm webm
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 144p MPEG-4 video/mp4 mp4
2020-10-02 23:56:09.593 6916-7032/su.sadrobot.yashlang I/System.out: 144p WebM video/webm webm
~~~

На 720p MPEG-4 плеер печатает эксепшен (я его не ловлю, похоже, это printStackTrace внутри плеера ExoPlayer):

~~~
2020-10-02 23:39:16.923 5883-6020/su.sadrobot.yashlang E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.ProtocolException: unexpected end of stream
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:359)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:182)
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:287)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:162)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:175)
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:182)
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:75)
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:271)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1083)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.ProtocolException: unexpected end of stream
        at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:396)
        at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.readInternal(DefaultHttpDataSource.java:696)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:357)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:182) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:91) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:287) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:162) 
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.advancePeekPosition(DefaultExtractorInput.java:175) 
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffInternal(Sniffer.java:182) 
        at com.google.android.exoplayer2.extractor.mp4.Sniffer.sniffFragmented(Sniffer.java:75) 
        at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.sniff(FragmentedMp4Extractor.java:271) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1083) 
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:975) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
~~~

Есть другие ролики, у которых тоже в списке 720p MPEG-4 и 360p MPEG-4 и они оба играют. Возможно, можно попробовать обновить плеер (это оказалось отдельной историей) или ловить этот эксепшен и, если поймали, грузить другой поток. Эксепшен в любом случае неплохо научитья ловить, т.к. на этом ролике плеер показывает черный экран и как бы загруженное видео, только нулевой длины, а было бы правильно показывать экран с ошибкой. Можно посмотреть события плеера.

Еще пример:

Чемпионат МВД России по стрельбе из боевого оружия - 2016
https://www.youtube.com/watch?v=nW6r0Mkb3MA

2020-10-02 23:06:44.950 31431-2021/su.sadrobot.yashlang I/System.out: 360p MPEG-4 video/mp4 mp4
2020-10-02 23:06:44.950 31431-2021/su.sadrobot.yashlang I/System.out: 720p MPEG-4 video/mp4 mp4

**Comment by sadr0b0t** [comment]
> С последним патчем не играют некоторые ролики - вот два:

в качестве фолбэка вот этот патч пока (оба ролика будут играть): https://github.com/sadr0b0t/yashlang/commit/f026fa327c17daac267895087288588543f784ca

но нужно его сделать лучше:
> // всю эту логику можно отработать в текущем потоке (thread) без обращения в интернет,
> // если кэшировать в VideoItem адрес не одного потока (stream), но и всех доступных потоков (stream)

**Comment by sadr0b0t** [comment]
По интерфейсу

- Норм вариант в мобильной браузерной версии Ютюба: в правом верхнем углу плеера шестренка (там есть место)
- По нажатии шестеренки всплывающий диаложек с разными настройками проигрывания
- Качество выбирается в выпадающем списке
- Вариант с выбором качества через меню PopupMenu совсем не хорош, т.к. среди доступных вариантов нужно отмечать уже выбранный (может быть, получится сделать, если передать в попап кастомный виджет для отображения элемента списка)
- Но кроме отмечания текущего элемента можно было бы там же показать остальные настройки: лучшее качество, наихудшее качество и тп. - для этого уже нужна полноценная панель, а не список.
- Высплывающий диалог попробовать реализовать через диалог подтверждения (или как он там называется - используется при подтверждении добавления ролика в черный список) - может быть получится добавить на него кастомную панель, но это не точно.

**Comment by sadr0b0t** [comment]
Про создание диалогов (можно сделать свой вью):
https://developer.android.com/guide/topics/ui/dialogs

**Comment by sadr0b0t** [comment]
выбирать поток видео в потоке плеера: https://github.com/sadr0b0t/yashlang/commit/c710cf0f06fe668cd3873ca9b5ace1b7e6d9f2f3

- по умолчанию всегда выбирает наилучшее качество
- помимо самой возможности выбирать нужный поток, появилась возможность для роликов Ютюб выбирать качество 1080p, которое раньше было не доступно, т.к. плеер выбирал и потоков видео, в которые была встроена дорожка аудио, а 1080p на ютюбовских видео шла без дорожки аудио (само аудио шло отдельным потоком с отдельным адресом)
- текущее качество отображается в текстовом поле: в портретном режиме в правом верхнем углу, в ландшафтном - в правом нижнем
- можно заменить на шестеенку (будет компактнее), но пока так норм
- настроек пока нет

**Comment by sadr0b0t** [comment]
настройки для автоматического выбора качества: https://github.com/sadr0b0t/yashlang/commit/c5a2789ee33a856f28568450129420e2619aae5d

**Comment by sadr0b0t** [comment]
фикс вдогонку: https://github.com/sadr0b0t/yashlang/commit/0f375de3c4d8a154b0824aa9f13ebe64407574e0
