### ISSUE TITLE
Играть контент через ссылки на торенты, плейлисты из списков на торенты

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#202]
Добавить возможность проигрывания контента, закачиваемого напрямую по торрент-ссылкам.

Или поискать библиотеки, которые могут качать такой поток и играть в плеере налету. Или добавить возможность качать такие ролики оффлайн, чтобы они потом появились в плейлисте как закачанные.

Торенты, как и остальные ролики, должны предварительно попадать в плейлисты. Формат такого плейлиста может быть простой текстовый файл со списком ссылок на торенты (одна ссылка - один ролик). Или, как вариант, один торент-файл с множеством файлов внутри.

Итоговая цель: добавить возможность играть контент с arjlover.net без дополнительных телодвижений прямо в приложении

**Comment by sadr0b0t** [comment]
18.01.2026
- в очередной раз пробую вернуться
  - текущая главная концепция - добавить проигрывание потоков с торрентов в реальном времени
    - если файл скачан локально, хороший вариант - иметь возможность его раздавать
  - пробую библиотеку torrent-stream
https://github.com/se-bastiaan/TorrentStream-Android
  - некоторое время назад (летом или весной) уже пробовал заходить на это направление
    - создал отдельный проект в Андроид Студии для первых тестов
    - и он сходу не скомпилировался - чистый проект вообще без зависимостей
    - сейчас еще раз открываю студию и тот проект
      - прочитал внимательнее сообщения об ошибках
      - нужно было исправить compileSdk на 33 с 31
    - студия еще что-то говорит о том, что для такой СДК неплохо обновить саму студию (плагин для Андроида)
      - но пока хрен с ним

**Comment by sadr0b0t** [comment]
23.04.2026

- мультики с multiki.arjlover.net качает
  - например:
https://multiki.arjlover.net/torrents/38.a.vdrug.poluchitsya.avi.torrent

- torrent-stream по сути никакой информации о закачиваемом ролике не дает
  - в смысле, в торренте изначально этой информации (название фильма, автор и т.п.) не предусмотрено
  - есть имя файла, пиры и т.п.
  - можно задавать ограничение скорости на закачку и раздачу
    - значит библиотека умеет раздавать
- значит для составления плейлистов из торрентов нужен еще файл с мета-информацией
  - в принципе, это и так бы требовалось, т.к. из отдельных торрентов или даже многофайловых торрентов нужно было создавать плейлисты
- отдельная проблема - откуда брать обложку
  - возможно, хороший вариант - класть в торрент рядом с роликом
    - это, конечно, для специально сформированных торрентов и в большинстве случаев это не будет доступно
    - хотя, возможно, какие-то торенты в таком виде уже формируют
      - нужно посмотреть на рутрекере
  - можно тянуть из википедии, кинопоиска, imdb и т.п.
    - еще film.ru рекомендует Черник
- вариант - импортировать многофайловый торрент как плейлист
  - не вижу, чтобы torrent-stream показывал информации о содержимом торрента, например, множественных файлах внутри
    - updt: список файлов есть:
> torrentStream.getCurrentTorrent().getFileNames()
  - даже если бы мог, все равно остаются проблемы с мета-информацией
  - скорее всего он должен уметь адресовать в url отдельные файлы внутри торрента
    - todo: проверить
  - скорее вариант такой, что список роликов со всей мета-информацией составляется руками как json отдельно
    - а torrent - это просто вариант адреса для закачки потока
  - но вариант импорта многофайлового торрента был бы ок, но в качестве запасного

**Comment by sadr0b0t** [comment]
- схема вырисовывается не такая сложная, как может показаться
  - загрузка плейлиста - загруза файла json с внешнего ресурса или из файла или из текстового поля
    - ядро кода - можно расширить функции экспорта/импорта, которые уже есть сейчас
      - там только сейчас сохранятся список самих плейлистов, но не роликов внутри
      - updt: вообще-то сами ролики тоже можно сохранять (но не импортировать)
        - канал ClassicCartoonsMedia так выкачивал - через сгенерированный скрипт
        - только сейчас смотрю бэкапы плейлистов - почему-то ролики не везде сохранял, а сохранял только списки плейлистов
          - а там, где сохранял, сохранял не в json, а sh и md
        - значит нужно взять формат такой же, в котором сохранял списки роликов
    - это можно обернуть API в NewPipeExtractor для единообразия
      - но это не точно, может, и без него получится
    - дальше загрузка контента - в зависимости от url потока
      - если поток обычный http, то старая схема
      - если ссылка на торрент - запуск процедуры загрузки
        - а ссылку в плеер на локальный файл
      - будет только гемор при переключении текущего места проигрывания
        - здесь, да, придется городить какую-то инфраструктуру вокруг плеера с обратной связью в закачки

- сделать редактор плейлиста с графическим интерфейсом?
  - веб-редактор с загрузкой локальный данных или локальный на электроне

**Comment by sadr0b0t** [comment]
- Внедряю torrent-stream в проект yashlang
  - пришлось поднять minSdkVersion с 17 до 21

- добавил временный код с добавлением плейлиста с роликами с url, указывающими на torrent
  - плейлист формируется в коде
  - теперь можно попробовать проигрывать такие ролики, когда они приходят в плеер

**Comment by sadr0b0t** [comment]
25.04.2026

a m, [24.04.2026 08:36]
https://github.com/se-bastiaan/TorrentStream-Android/issues/73
> Well this library only downloads any media file. Then you need to open the media file using exo player?
> Well no, you start downloading the torrent file using TorrentStream and then you open the video file in ExoPlayer. Exactly like the sample but with your own video player.

a m, [24.04.2026 08:40]
https://github.com/se-bastiaan/TorrentStream-Android/blob/develop/sample/src/main/java/com/github/se_bastiaan/torrentstreamer/sample/MainActivity.kt
- это пример кода с загрузкой ролика и проигрыванием
- открывает системный плеер после того, как ролик скачан целиком
- есть ощущение, что играть с середины до полной закачки в таком режиме не выйдет
- нужно ещё глянуть api torrent-stream, есть ли там вариант качать с указанного места

a m, [24.04.2026 08:41]
- посмотреть api exoplayer
-- может будет проще интегрировать работу с torrent-steam как-нибудь внутрь для стриминга
-- чем снаружи его прикручивать и синхронизивать ползунок с точкой загрузки торрента


- Торрент загружаю
  - в коде к плееру в промежуточном варианте подтянул
  - ExoPlayer отказывается играть avi загруженный
    - сначала думал, что, может, не доконца закачаный файл не играет
    - но, похоже, полностью закачаный тоже не играет
    - какая-то шляпа с кодеками у него
    - если скачанный файл забрать из эмулятора, то играет плеер на десктопе
    - это 38 попугаев
https://multiki.arjlover.net/torrents/38.a.vdrug.poluchitsya.avi.torrent

~~~
Playback error
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/mp4v-es, null, -1, null, [640, 480, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:193)
    at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.google.mpeg4.decoder
    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:193) 
    at android.os.HandlerThread.run(HandlerThread.java:65) 
Caused by: java.lang.IllegalStateException
    at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
    at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2698)
    at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1819)
    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989) 
    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:193) 
    at android.os.HandlerThread.run(HandlerThread.java:65) 
2026-04-25 16:52:09.940  9410-9449  ExoPlayerImplInternal   su.sadrobot.yashlang                 E  Disable failed.
~~~

**Comment by sadr0b0t** [comment]
https://stackoverflow.com/questions/76785121/androidx-media3-exoplayer-exoplaybackexception-mediacodecvideorenderer-error#77127468
https://github.com/google/ExoPlayer/issues/8987#issuecomment-1311420021
> Maybe you can try to call setEnableDecoderFallback(true) while creating the ExoPlayer object, it will try to find the available media codec from all the available codec lists. If you don't call setEnableDecoderFallback(true), the enableDecoderFallback is false, it will only use the first available codec and fails to init in some devices.
val exoPlayer = ExoPlayer.Builder(this) .setRenderersFactory(DefaultRenderersFactory(this).setEnableDecoderFallback(true)).build()
Reference - https://github.com/google/ExoPlayer/issues/8987#issuecomment-1311420021

**Comment by sadr0b0t** [comment]
так тоже все равно не играет
~~~java
exoPlayer = new ExoPlayer.Builder(this)
    .setRenderersFactory(new DefaultRenderersFactory(this).setEnableDecoderFallback(true))
    .build();
~~~
  - есть вероятность, что проблема только на эмуляторе, т.к. эта штука теоретически может пытаться использовать какие-то системные кодеки
    - стоит проверить на телефоне
    - открыл файл в системном плеере на эмуляторе (для этого перенес его в Загрузки - /sdcard/Download)
      - он его тоже не играет, правда, ошибку не пишет

**Comment by sadr0b0t** [comment]
- на телефоне качает
  - начал играть до того, как скачался целиком
    - файл отправляю в плеер на событие READY
      - я думал, это когда целиком файл скачается, а здесь, видимо, имеется в виду, что он готов играть
      - хотя откуда ему знать, когда файл готов играть? это же от кодека может только зависеть
  - но играет как-то очень странно - дергается туда-сюда
    - после того, как скачался целиком, все равно глючит
  - скачанный файл в системном плеере MiVideo так не глючит
  - это всё еще "38 попугаев"

- Айболит и бармалей
  - начал качать
  - событие READY нифига не возникает в начале закачки, ладно, еще нужно проверять
  - в итоге, вроде, выкачалось
  - начало играть в начале - слышно звук, видео не видно (возможно, это так в самом файле)
  - перемотал на середину, какой-то кадр было видно, потом показал какую-то ошибку
    - и после этого не могу вообще открыть ролик, т.к. он  все время показывает эту ошибку
    - а повторное открытие перебрасывает его на середину, а начать с начала с такой шляпой не могу

- поставил флаг setEnableDecoderFallback для версии на телефоне
  - (до этого отключал для чистоты эксперимента)
  - в плане проигрывания ничего не изменилось
    - вполне ожидаемо, т.к. кодек он выбирал в начале, просто этот кодек глючит

- ХЗ пока что с этим делать
  - остался вариант - обновить ExoPlayer
  - updt: обновил ExoPlayer до последней доступной версии (2.19.1 - 2023 год)
    - не помогло
    - более новых версий ExoPlayer нет, они говорят, что проект деприкейтыд и нужно переходить на Androidx Media3

**Comment by sadr0b0t** [comment]
- apk раздулся лихо с 12 Мб сразу до 30-ти
  - это один TorrentStream так постарался??
  - стоит глянуть, что у него в зависимостях там

- ExoPlayer 2.19.1 требует compileSdkVersion 33
  - до этого было compileSdkVersion 31
  - на совместимость со старыми андроидами, наверное, не должно влиять, поэтому фиг с ним

**Comment by sadr0b0t** [comment]
- поставил JustPlayer из F-Droid - на основе ExoPlayer
  - 38 попугаев avi колбасис так же
  - значит дело точно в ExoPlayer и avi
  - значит с другими торентами, в которых не avi, должно норм работать
    - но arjlover, конечно, жалко, если не заработает
https://github.com/TheDcoder/JustPlayer/releases
  - установил версию 0.201
    - в тегах такой нет, откуда на ф-дроиде взялась, хз
  - в версии 0.197 в зависимостях уже androidx.media3.exoplayer-dash
    - т.е. в относительно свежем exoplayer, переехавшем в androidx.media, все те же проблемы с avi
    - пробовать обновлять пока смысла нет

**Comment by sadr0b0t** [comment]
a m, [23.04.2026 14:25]
- для роликов при экспорте не сохраняется адрес иконки
-- скорее всего его нет и в базе данных
-- если сохранять адреса иконок для всех роликов, база вырастет очень заметно
-- но иконки предсказуемо можно тягать только с сервисов
-- если формировать плейлисты в json с произвольными путями иконок, их придется все равно сохранять в базу
-- добавить колонку к таблице роликов
-- или создать отдельную таблицу, чтобы при необходимости можно было их дропнкть легко?
--- пожалуй, этот вариант сомнительный, т.к. файл с базой все равно останется один
--- а выносить таблицу ещё в отдельную базу данных - уже совсем уродливо
-- ещё вариант - сохранять картинки локально в кэш сразу при загрузке плейлиста
--- увеличивает время и трафик добавления плейлиста, плюс сразу место занимает
--- плюс очистка кеша сразу обнуляет картинки роликов плейлиста без возможности восстановления
--- короче, этот вариант в минус

a m, [23.04.2026 14:28]
- формат импорта плейлистов придется доработать в любом случае
-- т.к. кроме ролика должно быть множество потоков для проигрывания разного качества
-- т.е. ссылка на торрент - это не ссылка на профиль ролика, как в Ютюбе и Пиртюбе, а ссылка на один из потоков
-- да, это все придется как-то хранить в базе данных тоже
-- возможно, с этим замечанием уже будет оправдано завести на них отдельную бд в отдельном файле
-- т.е. есть таблица импортированных плейлистов, а есть таблица с полной информацией о доступных плейлистах - вместо веб-сервиса

a m, [23.04.2026 15:26]
- хранить мета-информацию о плейлистах не локально, а тоже в торрентах
-- один фильм - один файл внутри торрента, который можно адресовать по id
-- id будет ассоциирован с фильмом - сохраняться локально и использоваться в качестве имени внутри торрента
-- собственно, как id ролика Ютюб или Пиртюб (то же самое - его полный url)
-- это будет замена централизованным сервисам
--- получается распределенная база данных с доступом по id
--- может уже такое есть??

a m, [23.04.2026 15:31]
- иконки для роликов можно тягать с внешних сервисов - imdb, kinopoisk и т.п. (если есть)
-- для каждого ролика хранить все id, которые известны
-- по ним и тягать иконки
-- но только ими ограничиваться нельзя, т.к. иначе не будет возможности иметь иконки для роликов, которых нет в этих базах
-- собственно, для львиной доли роликов их не будет, т.к. речь не только об онлайн--кинотеатре, а о просмотре любого контента
--- те же уроки по блендеру
--- да, что-то я увлекся прям фильмами, забыл про всё остальное

a m, [23.04.2026 15:31]
- и другой вариант - хранить их (иконки) во внешнем торренте тоже, как с метадатой выше вариант описан
-- тоже обращаться по имени файла, он же - id ролика внутри раздачи торрента
-- завести универсальный id для всех роликов, которые могут появиться в базе - на базе uuid
-- yashlang_id или ys_id

a m, [23.04.2026 15:35]
- вариант ещё хранить меиа-информаци и иконки на гитхабе
-- но очень ненулевая вероятность, что рано или поздно эту инфраструктуру оттуда выпилят
-- иконки за копирайт
-- а метаинфу - за ссылки на торенты

a m, [23.04.2026 16:07]
- инфраструктура обмена метаданными просится в блокчейн
-- контент - классические торренты

a m, [23.04.2026 16:08]
- как-то тут простой замены ссылок http на торенты уже не видно

a m, [23.04.2026 16:31]
- блокчейн нужен, чтобы добавлять новые элементы в плейлисты и патчить старые
-- т.к. торенты не меняются, их нужно при каждом обновлении или заменять полностью и делать серию патчей, как это делают в блокчейне
-- или как в Гите
-- в т.ч. правка старых элементов - исправления в названии, добавление новых дорожек, добавление id imdb, КиноПоиск и т.п.

**Comment by sadr0b0t** [comment]
a m, [24.04.2026 22:51]
- или вариант - не городить централизованно блокчейн, а оставить все на торрентах и ссылках
-- точнее, принципы те же, но полностью ручной режим
-- к примеру, один торрент с первой версией канала - это его первая версия
-- а следующий торрент с патчем - это обновление канала
-- т.е. это принцип блоков в блокчейне, но без определения специальной инфраструктуры
-- откуда выкачивать торренты с обновлениями канала - отдельный вопрос, но это может быть проблема юзера или распространителя
-- или получить файл через телегу, или скачать по известной ссылке, можно копипастой текст и т.п.
-- т.е. любые стандартные каналы передачи данных, ничего нового
-- как накладывать обновление канала на старую версию
--- точнее, как удостовериться, что это обновление подходит именно к этому каналу
--- можно использовать тоже механизмы блокчейна
--- открытый и закрытый ключ, уникальный uuid канала
--- т.е. сначала автор канала генерит uuid для канала, подписывает первую версию канала своим приватным ключом
--- потом выкидывает файл с обновлением - там тоже uuid и подпись
--- юзер качает обновление и применяет к базе - по uuid он находит сразу канал (если он уже добавлен), а по подписи он проверяет, от того ли автора пришло обновление
--- другой чел может подделать обновление, указав тот же uuid. Но оно не будет применено, т.к. не совпадет подпись

a m, [24.04.2026 23:23]
- по поводу сохранения потоков в базе
-- есть уже таблица stream_cache
-- там необходимая структура
-- но скидывать туда все содержимое канала всё-таки не очень хочется

**Comment by sadr0b0t** [comment]
a m, [25.04.2026 17:58]
https://stackoverflow.com/questions/76785121/androidx-media3-exoplayer-exoplaybackexception-mediacodecvideorenderer-error#77127468

a m, [25.04.2026 19:04]
https://github.com/google/ExoPlayer/issues/8987#issuecomment-1311420021

a m, [25.04.2026 21:01]
- нужно будет добавить в настройки просмотр занятого места в каталоге с торрентами и кнопку очистить
-- это для текущего просмотра
-- сохраненный кэш можно качать в стандартный каталог с кэшем

a m, [25.04.2026 22:00]
https://stackoverflow.com/questions/77271237/formates-avi-mpg-flv-wmv-support-issue-in-exoplayer-android

a m, [25.04.2026 22:03]
https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg

a m, [25.04.2026 22:07]
- короче, народ в принципе на поддержку avi в exoplayer жалуется

a m, [25.04.2026 22:07]
https://github.com/google/ExoPlayer/issues/6353

a m, [25.04.2026 22:07]
https://github.com/google/ExoPlayer/issues/6352

a m, [25.04.2026 22:09]
https://github.com/google/ExoPlayer/issues/2092
> The fact that AVI format is horribly outdated and nobody should use it is not going to deter our simple minded users! ~7% of the files that my users try to play every day are AVI. With 20k DAU, this is insane. I get at least one 1-star review everyday specifically about this.

**Comment by sadr0b0t** [comment]
a m, [28.04.2026 00:01]
Formates (AVI, MPG, FLV, WMV) support issue in ExoPlayer-Android
https://stackoverflow.com/questions/77271237/formates-avi-mpg-flv-wmv-support-issue-in-exoplayer-android
> Hay, I'm developing a video player in Android Kotlin using ExoPlayer. All works fine except some video formats ( AVI, MPG, FLV, WMV). Is there some workaround of making a decoder or codecs ,that can play these formats? or something else to play these formats in my player.
I tried converting video formats with FFmpeg but it took so much time to convert a video. so I am trying to make a decoder or any codec to play these kind of formats. Any help appreciated, thank you.

> Using FFmpeg is the right choice, however, you don't need to convert a file.
Instead, you should use ExoPlayer Fmpeg extension to play media files:
https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg
There is a modification that supports video files:
https://github.com/AhmedHumk/ffmpegVideoDecoder
and
https://github.com/anilbeesetti/nextlib

> i am using this github.com/anilbeesetti/nextlib & it is already using decoder_ffmpeg, but still the mentioned formats are not playing. can you guide me some more if i am missing something. or is there any thing to add in nextlib player to play these formats.

a m, [28.04.2026 00:04]
https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg

a m, [28.04.2026 00:04]
https://github.com/AhmedHumk/ffmpegVideoDecoder

a m, [28.04.2026 00:04]
https://github.com/anilbeesetti/nextlib

a m, [28.04.2026 00:05]
https://www.reddit.com/r/RedditEng/comments/1af2d8d/improving_video_playback_with_exoplayer/

**Comment by sadr0b0t** [comment]
Внезапная проблема - все или подавляющее большинство мультиков/фильмов на rutracker.org, rutor.net, multiki.arjlover.net, если они упакованы отдельными роликами или пачками роликов, выложены в формате avi. Значит с проигрыванием avi нужно что-то делать или искать раздачи на других трекерах (что-то может быть на thepriratebay.org, но там не так системно).

**Comment by sadr0b0t** [comment]
Проект nextlib сразу с версии 0.1.0 использовал androidx.media3 (а не старый ExoPlayer)
https://github.com/anilbeesetti/nextlib/blob/v0.1.0/ffcodecs/build.gradle.kts
~~~
    implementation(libs.androidx.media3.exoplayer)
~~~

поэтому чтобы его попробовать придется обновить ExoPlayer до androidx.media3

самая ранняя версия - 1.1.0
~~~
https://github.com/anilbeesetti/nextlib/blob/v0.1.0/gradle/libs.versions.toml
~~~

**Comment by sadr0b0t** [comment]
https://developer.android.com/media/media3/exoplayer/hello-world
https://github.com/androidx/media

**Comment by sadr0b0t** [comment]
Обновил ExoPlayer до media3 1.2.0 https://github.com/sadr0b0t/yashlang/issues/227 (чтобы не повышать minSdkVersion) и потом в экспериментальном коде - на максимальную 1.10.0. Легче не стало.

Подключил nextlib максимальной версии 0.8.4. На проигрывание тестового файла avi (38 попугаев https://multiki.arjlover.net/torrents/38.a.vdrug.poluchitsya.avi.torrent) никак не повлияло

~~~
implementation("androidx.media3:media3-exoplayer:1.10.0")
implementation("androidx.media3:media3-exoplayer-dash:1.10.0")
implementation("androidx.media3:media3-ui:1.10.0")

implementation("com.github.anilbeesetti.nextlib:nextlib-media3ext:v0.8.4")
implementation("com.github.anilbeesetti.nextlib:nextlib-mediainfo:v0.8.4")
~~~

вариант с nextlib
~~~java
exoPlayer = new ExoPlayer.Builder(this)
        .setRenderersFactory(new NextRenderersFactory(this))
        .build();
~~~

вариант без nextlib
~~~java
exoPlayer = new ExoPlayer.Builder(this)
        .build();
~~~

Дают один и тот же результат.

Это значит, что для тестового avi кодек из nextlib не загрузился, или в базовом ExoPlayer для этого файла используется тот же кодек, что в nextlib.

apk при этом раздулся до 100 Мб (вместе с torrent-stream) с 12 исходных.

Еще один неплохой минималистичный плеер на основе nextlib https://github.com/anilbeesetti/nextplayer - дает тот же самый глюк при проигрывании avi, что и приложение с подключенным nextlib. Можно было изначально проверить файл avi на нем. Интересно, что apk плеера всего 18 Мб. С отключенным nextlib apk всё те же 93 Мб. Файл вырос примерно с 50 Мб (вместе с torrent-stream) до 93 Мб при обновлении media3 ExoPlayer с 1.2.0 до 1.10.0.

В целом, nextlib в таком случае не нужен. По крайней мере, не обязателен.

Difference between Nextlib and Media3 FFmpeg extension? #149
https://github.com/anilbeesetti/nextlib/issues/149
> basically this library support wide format
Audio: Vorbis, Opus, Flac, Alac, pcm_mulaw, pcm_alaw, MP3, Amrnb, Amrwb, AAC, AC3, EAC3, dca, mlp, truehd
Video: H.264, HEVC, VP8, VP9
but ffmpeg in media 3 only support few audio format it 100% not play HEVC videos exoplayer team told i have to build it via linux os and create arr that is big process but tis library simplify this. you get all in one video encoder and audio encoder instead of adding 4-5 arr files.


https://github.com/moneytoo/Player
> Unfortunately, upstream ExoPlayer doesn't handle some older formats like AVI container, WMV or Theora. Majority of devices also cannot handle 10-bit AVC.

Support AVI #2092
https://github.com/google/ExoPlayer/issues/2092
> Initial support is ready and will be released soon. But as explained in #9915, support is incomplete and we'll need support from the community to report (and ideally send PRs for) any issues you encounter.
> EDIT: AVI support exists in the dev branch.

Add AVI extraction support #9915
https://github.com/google/ExoPlayer/pull/9915


Что они имеют в виду под "в разработке" сейчас уже не очень ясно - было ли это с тех пор опубликовано или все еще в каких-то экспериментальных ветках.

Текущий итог:
- тестовый AVI 38 попугаев с последней версией ExoPlayer нормально не играет. Подключение nextlib не спасает
- есть вероятность, что это может быть исправлено в экспериментальных версиях ExoPlayer, но она зыбкая
- нужно провести еще тесты на других AVI из других источников
- если вообще ни с какими AVI не срастется, искать/делать торренты не с AVI

**Comment by sadr0b0t** [comment]
Попробовал еще пару avi'шек. Одна ровно так же дергается, одна вообще не загрузилась (NextPlayer, JustPlayer)

**Comment by sadr0b0t** [comment]
Playback of AVI files fails most of the time. https://github.com/androidx/media/issues/164

**Comment by sadr0b0t** [comment]
a m, [29.04.2026 14:26]
[BUG] Error: can't play video
https://github.com/anilbeesetti/nextplayer/issues/982
> @dexaltat You should really be using x264 or x265 mkv files instead. They look better and are smaller. AVI isn't being supported natively by Media3.

a m, [29.04.2026 14:31]
Not able to play video with this codec Stream 0: Codec: H264 - MPEG-4 AVC (part 10) (avc1), Stream 1 Codec: PCM MU-LAW (mlaw)
https://github.com/moneytoo/Player/issues/581
> Why do you guys insist in playing old formats on phones that can play all the new formats? Upgrade your videos. Your phone can play the new formats just fine. Just Player is using media3 which doesn't support those old AVI and mlaw formats.
If you need to play an old format that badly, use another player like https://github.com/mpv-android/mpv-android which uses mpv.

a m, [29.04.2026 14:34]
Avi support
https://github.com/moneytoo/Player/issues/298
> While the AVI container is somehow supported, it is mostly paired with older audio and video codecs which often may not be playable on current Android devices. To confirm this, state your device model and ideally share a video sample (or at least MediaInfo output).

> Latest version 0.128 (https://github.com/moneytoo/Player/releases/tag/v0.128) includes Media3Avi (https://github.com/dburckh/Media3Avi), which is the most what can be done regarding support of Avi as of today.

a m, [29.04.2026 14:37]
AVI Video not playing at all
https://github.com/moneytoo/Player/issues/354

a m, [29.04.2026 14:40]
https://github.com/dburckh/Media3Avi
> Library with improved AVI support for Jetpack Media3 (formerly ExoPlayer)
Port of my original AVI library to support Media3. Although ExoPlayer/Media3 now has AVI support, it is quite limited. This should support most AVI files.
- выглядит очень хорошо
- но судя по тому, что выше написано, что она была встроена в JustPlayer ещё в 2022, и он сейчас нормально avi не играет, это тоже не поможет
- оставшаяся надежда - найти проигрываемые avi (возможно, по кодекам определенным) или найти торренты без avi

a m, [29.04.2026 16:41]
https://github.com/mpv-android/mpv-android
> mpv-android is not a library/module (AAR) you can import into your app.
If you'd like to use libmpv in your app you can use our code as inspiration. The important parts are MPVLib (https://github.com/mpv-android/mpv-android/blob/master/app/src/main/java/is/xyz/mpv/MPVLib.kt), BaseMPVView (https://github.com/mpv-android/mpv-android/blob/master/app/src/main/java/is/xyz/mpv/BaseMPVView.kt) and the native code (https://github.com/mpv-android/mpv-android/blob/master/app/src/main/jni). Native code is built by these scripts (https://github.com/mpv-android/mpv-android/blob/master/buildscripts).

**Comment by sadr0b0t** [comment]
Попробовал Media3Avi

~~~
    implementation 'com.github.dburckh:Media3Avi:2.3.0'
~~~
~~~java
    exoPlayer = new ExoPlayer.Builder(this)
            // Core AVI Support
            .setMediaSourceFactory(new DefaultMediaSourceFactory(this, new AviExtractorsFactory()))
            // Optional MJPEG Support
            .setRenderersFactory(new MjpegRenderersFactory(this))
            .build();
~~~
с AVI та же история
