### ISSUE TITLE
NullPointerException при открытии видео из списка "Новое" или из недобавленного в базу плейлиста

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#32]
~~~
    Process: su.sadrobot.yashlang, PID: 542
    java.lang.NullPointerException: Attempt to invoke virtual method 'long su.sadrobot.yashlang.model.VideoItem.getId()' on a null object reference
        at su.sadrobot.yashlang.WatchVideoActivity.playVideoItem(WatchVideoActivity.java:1194)
        at su.sadrobot.yashlang.WatchVideoActivity.access$200(WatchVideoActivity.java:92)
        at su.sadrobot.yashlang.WatchVideoActivity$13$1.run(WatchVideoActivity.java:594)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
~~~

**Comment by sadr0b0t** [comment]
Пусть будет здесь же:

Если открывать так Питрубовский ролик, при при загрузке он не вылетает и даже играет, но остаётся кнопка "вправо" при нажатие на которую вылетает эксепшен (во-первых, экспепшен в любом случае не должен вылетать, во-вторых, в этом режиме кнопки вправо не должно быть):

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.RecyclerView$Adapter.getItemCount()' on a null object reference
 at su.sadrobot.yashlang.WatchVideoActivity$4.onClick(WatchVideoActivity.java:261)
 at android.view.View.performClick(View.java:6266)
 at android.view.View$PerformClick.run(View.java:24730)
 at android.os.Handler.handleCallback(Handler.java:793)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6701)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
~~~

**Comment by sadr0b0t** [comment]
Здесь же: в режиме проигрывания недобавленного ролика в меню остаётно звездочка и элементы "добавить в блеклист", "скопировать адрес плейлиста" и т.п. (их лучше убрать)

**Comment by sadr0b0t** [comment]
Первый эксепшен исчез на одном из коммитов после 0.1.0. Специально не исправлял, но в этой области были правки, ну и ладно. Проверил: в текущей версии открываю видео из недобавленного плейлиста - не вылетает, откатился на версию 0.1.0, открываю это же видео - вылетает, возвращаюсь к текущей версии - опять не вылетает.

С первым откатом до 0.1.0 проебал базу с плейлистами и историей просмотров на телефоне, которая копилась больше года начиная с первых версий до релиза, как жаль.

Во-первых, в VideoDatabase.java нужно было выключить fallbackToDestructiveMigration() (сейчас выключил, так больше происходить не будет, но только при откате на версии старше 0.1.0, откат на 0.1.0 теперь всегда будет обнулять базу)

Во-вторых, нужно было скачать файл с базой данных из /data/data/su.sadrobot.yashlang/databases/video-db в телефоне в FileExplorer, ведь только вчера его выкачивал так, но, к сожалению, только с эмулятора, ай, ай.

**Comment by sadr0b0t** [comment]
исходный баг закрываю, остальное перенес сюда: https://github.com/sadr0b0t/yashlang/issues/37
