### ISSUE TITLE
IllegalStateException на экране Search

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#33]
Делал поиск, стирал старые результаты, начал вводить новый текст, словил эксепшен. Просто так не воспроизвести.

~~~
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:524)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:90)
	at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:340)
	at androidx.room.paging.LimitOffsetDataSource.loadInitial(LimitOffsetDataSource.java:135)
	at androidx.paging.PositionalDataSource.dispatchLoadInitial(PositionalDataSource.java:286)
	at androidx.paging.TiledPagedList.<init>(TiledPagedList.java:107)
	at androidx.paging.PagedList.create(PagedList.java:229)
	at androidx.paging.PagedList$Builder.build(PagedList.java:388)
	at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
	at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
	at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
~~~

**Comment by sadr0b0t** [comment]
Поймал еще раз
~~~
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
 at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
 at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
 at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:524)
 at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:90)
 at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:340)
 at androidx.room.paging.LimitOffsetDataSource.loadInitial(LimitOffsetDataSource.java:135)
 at androidx.paging.PositionalDataSource.dispatchLoadInitial(PositionalDataSource.java:286)
 at androidx.paging.TiledPagedList.<init>(TiledPagedList.java:107)
 at androidx.paging.PagedList.create(PagedList.java:229)
 at androidx.paging.PagedList$Builder.build(PagedList.java:388)
 at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
 at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
 at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 at java.lang.Thread.run(Thread.java:764)
~~~

**Comment by sadr0b0t** [comment]
Получается воспроизвести:
1. Зайти в поиск
2. Выбрать "играть всё" => откроется в экране плеера
3. Кликнуть два раза на экране плеера пока грузится видео (полный экран, выйти из полного экрана)
4. Сразу нажать "назад" на тулбаре
5. Немного подождать

результат: приложение вылетает с эксепшеном

Пункт 3 скорее всего дает нужную паузу, т.к. если сразу нажать "назад", эксепшен может не прилететь.

**Comment by sadr0b0t** [comment]
Возможно, у этого бага такая же причина: https://github.com/sadr0b0t/yashlang/issues/38

Незавершенные фоновые потоки после выхода из активити? Там dbconnection закрывается в onDestroy, нужно проверить, что вызывается раньше - onDestroy или завершается поток какой-нибудь фоновый.

**Comment by sadr0b0t** [comment]
> Возможно, у этого бага такая же причина:
> Незавершенные фоновые потоки после выхода из активити? Там dbconnection закрывается в onDestroy, нужно проверить, что вызывается раньше - onDestroy или завершается поток какой-нибудь фоновый.

это стопудово так - сначала вызывается onDestroy, а фоновые потоки продолжают работать, см здесь: https://github.com/sadr0b0t/yashlang/issues/36#issuecomment-731567500

Если в активити был общий объект videodb, который закрывался в onDestroy (исправлено здесь: https://github.com/sadr0b0t/yashlang/issues/38), то да, фоновые потоки после закрытия активити могли пробовать обращаться в закрытому в onDestroy подключению videodb, что могло приводить к непредсказуемым вылетам.

**Comment by sadr0b0t** [comment]
Сейчас постоянно вылетает (возможно из-за того, что надобавлял много плейлистов)

**Comment by sadr0b0t** [comment]
фикс: https://github.com/sadr0b0t/yashlang/commit/f16fa255242b01e09d5bbd9eafb25a49c7ee0f4b
подробности: https://github.com/sadr0b0t/yashlang/issues/68
