### ISSUE TITLE
В режиме проигрывания роликов из недобавленных плейлистов не должно быть кнопки "вправо"

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#37]
При открытии видео из списка "Новое" или из недобавленного в базу плейлиста:

- остаётся кнопка "вправо"
- при нажатии на которую вылетает эксепшен:

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.RecyclerView$Adapter.getItemCount()' on a null object reference
 at su.sadrobot.yashlang.WatchVideoActivity$4.onClick(WatchVideoActivity.java:261)
 at android.view.View.performClick(View.java:6266)
 at android.view.View$PerformClick.run(View.java:24730)
 at android.os.Handler.handleCallback(Handler.java:793)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6701)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
~~~

(во-первых, экспепшен в любом случае не должен вылетать, во-вторых, в этом режиме кнопки вправо не должно быть)

Здесь же: в меню остаётно звездочка и элементы "добавить в блеклист", "скопировать адрес плейлиста" и т.п. (их лучше убрать)

**Comment by sadr0b0t** [comment]
Даже если спрятать кнопку, эксепшен вылетит при завершении ролики при попытке переключиться на следующий

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.recyclerview.widget.RecyclerView$Adapter.getItemCount()' on a null object reference
 at su.sadrobot.yashlang.WatchVideoActivity$9.onPlayerStateChanged(WatchVideoActivity.java:406)
 at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
 at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate$$Lambda$5.invokeListener(Unknown Source:2)
 at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
 at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
 at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
 at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
 at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
 at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
 at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
 at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
 at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
 at android.os.Handler.dispatchMessage(Handler.java:105)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6701)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
~~~

**Comment by sadr0b0t** [comment]
Фикс кнопки, экспепшена и вообще перераотал механизм управления видимостью элементов управления: https://github.com/sadr0b0t/yashlang/commit/a839410e35d0b2b3dbc5aaffe4def300359ca43b

**Comment by sadr0b0t** [comment]
> Здесь же: в меню остаётно звездочка и элементы "добавить в блеклист", "скопировать адрес плейлиста" и т.п. (их лучше убрать)

Готово: https://github.com/sadr0b0t/yashlang/commit/55bda6f66588f5fd12095ae27ed901c49201ec70

Получился хороший рефактор и еще дополнительные исправления в поведении меню
