### ISSUE TITLE
Профили включения плейлистов

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#41]
Много плейлистов в одних только рекомендованных уже. Нужно с ними управляться как-то так, чтобы можно было удобно включать и выключать комбинации плейлистов, при этом не листать весь список и тыкать вкл-выкл. Например режим - показывать только Мультики, показывать только Кино и т.п.

Хороший вариант - завести механизм профилей. Будет новая вкладка в настройках. Каждый профиль будет содержать набор плейлистов. Переключение профиля будет включать плейлисты из наборы и выключать все остальные.

Например, можно будет завести профиль "Мультики" и добавить туда все плейлисты и каналы, на которых только мультики. Или еще дополнительно "Мультики для малаший" и там будут плейлисты с мультиками для совсем мелких малышей. Профиль "лекции" будет включать плейлисты с лекциями, профиль "Музыка" - только с музыкой и т.п.

Дополнительно - встроенные (неудаляемые и ненастраиваемые) профили:
- Включить всё - включить все плейлисты
- Выключить всё - выключить все плейлисты (полезно, например, если хочется потом включить несколько плейлистов вручную, но при этом не создавать для них профиль)
- Выключить плейлисты Ютюб - выключить все плейлисты Ютюб, остальные (Пиртюбовские) оставить без изменений (полезно в ситуациях, когда Гугл в очередной раз сломает АПИ, в таком случае в выдаче рекомендацию будут появляться только Пиртюбовские ролики, а Ютюбовские ролики не будут засорять выдачу ошибками).

**Comment by sadr0b0t** [comment]
Первый шаг для профилей: https://github.com/sadr0b0t/yashlang/commit/af0d27413e174d94b56e85d349400b8755725324

- Вкладка "Профили"
- И три кнопки: "Вклють ВСЕ", "Выключить ВСЕ", "Выключить все YouTube"

здесь же перенес функцию включения/выключения плейлиста (она правит обе таблицы - в роликами и с плейлистами) в PlaylistInfoDao в транзакцию @Transaction (пофиксил TODO давнишний в коде)

**Comment by sadr0b0t** [comment]
Есть профили плейлистов: https://github.com/sadr0b0t/yashlang/commit/431f220a337446a3ee6611ebe06ac34a491e595e

- Применить профиль: выключить все плейлисты, включить только плейлисты из профиля
- Добавить к выбранном: включить плейлисты из профиля, другие уже включенные не выключать
- Добавить, изменить, удалить профиль - понятно
- Включить все, выключить все, выключить все YouTube - встроенные неудаляемые профили (на самом деле не совсем профили, но отображаются в списке остальных профилей всегда наверху, в списке отделены разделительной полоской)


Не реализовано/исправить:
- При добавлении профиля не успевает обновить список на экране со списком профилей, т.к. обновляет список при активации экрана, а добавление происходит в фоновом потоке (правильное решение - использовать PagedListAdapter вместо ArrayAdapter, но в таком случае не получается легко встроить фейковые профили "выключить все", "выключить все" и "выключить все ютюб")
- Иконки профилей (можно сделать динамически: например, подгружать иконку первого включенного плейлиста или первых 2-3-х плейлистов и рисовать их как-нибудь стопкой или сделать анимацию со сменой иконок включенных плейлистов или как-то еще)
- Поймал один раз эксепшен во время разработки (больше не ловил с тех пор, но, вроде, для исправления тоже особо ничего не менял)

~~~
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
	at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
	at su.sadrobot.yashlang.model.ProfileDao_Impl.addPlaylistToProfile(ProfileDao_Impl.java:199)
	at su.sadrobot.yashlang.model.ProfileDao.setPlaylists(ProfileDao.java:81)
	at su.sadrobot.yashlang.model.ProfileDao_Impl.access$001(ProfileDao_Impl.java:25)
	at su.sadrobot.yashlang.model.ProfileDao_Impl.setPlaylists(ProfileDao_Impl.java:159)
	at su.sadrobot.yashlang.model.ProfileDao.update(ProfileDao.java:97)
	at su.sadrobot.yashlang.model.ProfileDao_Impl.access$201(ProfileDao_Impl.java:25)
	at su.sadrobot.yashlang.model.ProfileDao_Impl.update(ProfileDao_Impl.java:182)
	at su.sadrobot.yashlang.ConfigureProfileActivity$5.run(ConfigureProfileActivity.java:251)
	at java.lang.Thread.run(Thread.java:764)
~~~

**Comment by sadr0b0t** [comment]
обновил ридми
https://github.com/sadr0b0t/yashlang/commit/e6addf671249355afe4a0f19cfa4340ce5281f32
