### ISSUE TITLE
NullPointer при редактировании адреса плейлиста

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#43]
Если, например, быстро удалять символы уже введенного адреса можно с высокой долей вероятности словить NullPointer

~~~
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String su.sadrobot.yashlang.model.PlaylistInfo.getName()' on a null object reference
 at su.sadrobot.yashlang.AddPlaylistActivity$13$1.run(AddPlaylistActivity.java:453)
 at android.os.Handler.handleCallback(Handler.java:793)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:6701)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
~~~

добавил в 0.2.0 здесь: https://github.com/sadr0b0t/yashlang/issues/6 https://github.com/sadr0b0t/yashlang/commit/d5ca78dbab4cc6bdccb40601657849b1934277be

**Comment by sadr0b0t** [comment]
здесь фикс https://github.com/sadr0b0t/yashlang/commit/25c20c5d8c7d569aeb20e3599bf2223260d95e43

нормально проверить не получается, т.к. исходная проблема перестала воспроизводиться
