### ISSUE TITLE
IndexOutOfBoundsException при проверке "новое" для всех плейлистов

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#64]
~~~
    Process: su.sadrobot.yashlang, PID: 31677
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at su.sadrobot.yashlang.view.VideoItemMultPlaylistsOnlyNewOnlineDataSource.loadInitial(VideoItemMultPlaylistsOnlyNewOnlineDataSource.java:81)
        at androidx.paging.ItemKeyedDataSource.dispatchLoadInitial(ItemKeyedDataSource.java:254)
        at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
        at androidx.paging.PagedList.create(PagedList.java:216)
        at androidx.paging.PagedList$Builder.build(PagedList.java:388)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
        at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
        at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
~~~

**Comment by sadr0b0t** [comment]
https://github.com/sadr0b0t/yashlang/commit/52f8706ba15dc2c1c1d40b410de737162c1390a8
