### ISSUE TITLE
Перенос данных приложения между устройствами или бэкап и загрузка на одном устройстве

### ISSUE THREAD

**Issue by sadr0b0t** [sadr0b0t/yashlang#9]
- Предпочительный вариант: найти штатный способ сохранить данные приложения и потом подсунуть их в качестве исходных данных вновь уставновленной версии того же приложения, чтобы работало на любом андроиде (без использования проприетарных облаков от производителей устройств). Если такой найдется, добавить его в документацию

- Если первый вариант не найдется, реалиовать экспорт/импорт данных (плейлисты, история просмотров и т.п. - всё структуры б/д) внутри приложения.

Кроме того, чтобы иметь возможность переносить коллекцию плейлистов с устройства на устройство, без этой возможности не получится переключиться между версиями приложения из разных источников из-за разных подписей apk (сейчас, правда, на F-Droid до сих пор не выложили пока, поэтому переключаться с релизов github не на что).

В NewPipe процесс экспорта/импорта данных описывают так
https://github.com/TeamNewPipe/NewPipe

> 1. Back up your data via "Settings>Content>Export Database" so you keep your history, subscriptions, and playlists
> 2. Uninstall NewPipe
> 3. Download the APK from the new source and install it
> 4. Import the data from step 1 via "Settings>Content>Import Database"

Но я у себя в телефоне (Сяоми) такой опции что-то не нашел. Может плохо искал, нужно проверить.

**Comment by sadr0b0t** [comment]
Для начала можно сделать простой экспорт текстом: список плейлистов в формате "имя плейлиста" + "адрес плейлиста" и списка любимых видео (тоже: имя + адрес).

**Comment by sadr0b0t** [comment]
Экспорт одного плейлиста (всех его роликов) в текст - в клипборд, добавил временно в ViewPlaylistActivity на скорую руку в onCreate, пусть пока будет здесь, чтоб не потерялось

~~~java
        Toast.makeText(this, "" + playlistId, Toast.LENGTH_LONG);
        if (playlistId != -1) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    java.util.List<VideoItem> items = videodb.videoItemDao().getByPlaylist(playlistId);
                    final StringBuilder plStr = new StringBuilder();
                    for(int i = 0; i < items.size(); i++){
                        final VideoItem vid = items.get(i);
                        plStr.append(i).append("\t").append(vid.getName()).append("\t").append(vid.getThumbUrl()).append("\t").append(PlaylistUrlUtil.getVideoUrl(vid.getYtId())).append("\n");
                    }
                    handler.post(new Runnable() {
                        @Override
                        public void run() {
                            final ClipboardManager clipboard = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE);
                            final ClipData clip = ClipData.newPlainText(""+playlistId, plStr.toString());
                            clipboard.setPrimaryClip(clip);
                        }
                    });

                }
            }).start();
        }
~~~

**Comment by sadr0b0t** [comment]
Посмотреть текущую структуру бызы:
    //   - файл с базой /data/data/su.sadrobot.yashlang/databases/video-db
    //   - выкачать на компьютер
    //   - из эмулятора в Android Studio: справа внизу вкладка Device File Explorer
    //   - на компьютере - открыть в любом редакторе файлов баз SQLite
    //   - например: "DB Browser for SQLite" или Sqliteman есть в репозитории Убунты
    //   - можно переименовать файл - добавить расширение ".db" video-db.db
    //       (нужно было сразу так назвать, сейчас уже поздно)
    //   - "DB Browser for SQLite" лучше, позволяет смотреть структуру базы, в т.ч.
    //       типы данных и настройки колонок (показывает команду создания базы) и выполнять запросы SQL

Файл можно выкачивать и сохранять и можно потом обратно заменить на устройстве на старый бэкап.

Может сработать на некоторых устройствах (возможно, потребуется включить режим разработчика), но на других устройствах может не хватить прав даже на чтение.

**Comment by sadr0b0t** [comment]
- Для экспорта можно добавить отдельную вкладку в настройках (теперь там появились вкладки - вторая вкладка "Новое")
- Экспортировать "Любимое", список плейлистов (имя, адрес, иконка)
- Возможно, историю просмотров (?) -( если только отдельной опцией)
- Дополнительно: экспортировать плейлист со всем содержимым
- Формат данных - JSON (опционально - построчно?)
- Все опции экспорта можно совмещать в одном файле

При импорте:
- При импорте "любимое" Матчить видео по идентификатор в сервисе + плейлист (опционально - только по идентификатору)
- Вариант импорта плейлиста оффлайн (если экспортирован весь список видео) или онлайн (загрузка содержимого онлайн, как при обычном добавлении)
- Отдельная панель последовательного импорта плейлистов из файла со списком плейлистов, прогрессом, панельками ошибок и прочими делами
- Возможно, совместить с экраном добавления рекомендованных плейлистов
- Или даже просто взять его за основу, при этом рекомендованные плейлисты перенести в файл в описанном выше формате.
- Возможно, при пустом списке плейлистов показывать кнопку "Импортировать из файла" рядом с "Добавить рекомендованное"

**Comment by sadr0b0t** [comment]
Экспорт в Markdown и скрипты sh с youtube-dl: https://github.com/sadr0b0t/yashlang/commit/0802b52471a7a786f91f049421b8aff2471572e5

Пока в экспериментальном режиме, но, в целом, работает ок.

Экран экспорта: Настройки > меню "Экспорт"

На моем смартфоне файлы попадают на внешнее хранилище > Android/data/su.sadrobot.yashlang/files

Каталог можно открыть в менеджере файлов и из него переслать их куда-нибудь еще (например, в NextCloud и т.п.).

TODO:
- убрать плашку "this feature is experimental", когда формат файлов устаканится
- настройки включить/выключить "имена роликов"/"адреса url роликов" распространить так же на экспорт списка "любимые" и "черный список" (сейчас они действуют только на "плейлисты с элементами")
- экспортировать историю (?)
- дополнительные поля для плейлистов (?): например, количество элементов в плейлисте, ссылка на иконку и т.п. (возможно, здесь этим не стоит заморачиваться, все данные из базы пойдут в формат JSON)
- в варианте с Markdown фантазия сразу рисует всякие отчеты об использовании программы в формате веб md->HTML, пожалуй, пока не стоит этим увлекаться
- сохранять настройки чекбоксов экспорта
- формат plain text (без ссылок) (?)
- экспортировать в JSON (имеет смысл реализовать сразу вместе с импортом, поэтому задача потяжеловеснее)

**Comment by sadr0b0t** [comment]
Экспортировать на pastebin?

**Comment by sadr0b0t** [comment]
Экспортировать профили: 1ea76b86d82c16a84837a548061f8752ca4879d3

**Comment by sadr0b0t** [comment]
https://github.com/sadr0b0t/yashlang/commit/e5ce111f869a65c02c3dc54227ab2c8b67aa1363

- Экспорт в JSON
- Импорт списка плейлистов из JSON - список роликов загружается онлайн
- Вариант сохраниния в буфер обмена и импорт из буфера обмена (если там скопирован JSON)

TODO
- формат данных явно не оптимальный, данные дублируются - например, список плейлистов есть отдельный и есть с полным списком роликов, под нормальный экспорт нужно будет переработать интерфейс с галками
- Звездочки, черный список, история просмотров, профили и т.п. не импортируются

**Comment by sadr0b0t** [comment]
Здесь косяк. Т.к. передаю в активити для импорта загруженную строку, а не сам файл, получаю эксепшен, если содержимое файла слишком велико (например, если в нем сохранены сами ролики, а не только список плейлистов).

Вылетает без эксепшена внутри приложения.

~~~
2021-08-25 12:16:16.165 1722-2143/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 542776)
2021-08-25 12:16:16.166 1722-2143/? E/ActivityManager: Second failure launching su.sadrobot.yashlang/.ImportPlaylistsActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 542776 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:758)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1236)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1533)
        at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:1007)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:7304)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:7371)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:292)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3055)
        at android.os.Binder.execTransact(Binder.java:681)
~~~

**Comment by sadr0b0t** [comment]
этот вариант пусть будет отдельным тикетом https://github.com/sadr0b0t/yashlang/issues/96

> Про экспорт/импорт как есть файла с базой данных. В ручном режиме это получится сделать далеко не на всех устройствах - тивоизированные нерутованные девайсы не пустят Device File Explorer в каталог приложения.
> 
> Но можно же сделать это из самого приложения. Добавить вкладку на Экспорте, прочитать приватный файл с б/д из внутренний памяти и скопировать его в публичную зону на флешку. Обратно таким же образом. Работу б/д при этом лучше как-нибудь приостановить.
> 
> В таком случае не нужно возиться с переносом каждой из настроек. А экспорт в Markdown или скрипт youtube-dl останется для удобства. И JSON.

**Comment by sadr0b0t** [comment]
В NewPipe в зависимостях какой-то файл-пикер
https://github.com/TeamNewPipe/NewPipe/blob/dev/app/build.gradle

~~~
implementation 'com.github.TeamNewPipe:NoNonsense-FilePicker:5.0.0
~~~

можно на него посмотреть
